# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c8abb3ddb5d9dd963a868b931f83ff0d591d855f49c4bcd5fc2c96bfe94ed229635c5240994cd05a5833a9066e3ca66e3ee87bee56eb34e88e88343c63791b

test:
  secret_key_base: 664c2086665ef6f209c7ea93879f897ec7fd9bf8893c91d7094d96a9e832f33fd38c48e9772f700f786b4e2ffc810dddc8028802667977cd93f182257693c9b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
